version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:30"
  reviewers:
  - gilbertly
  labels:
  - dependabot
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: gatsby-theme-apollo-docs
    versions:
    - 4.5.12
    - 4.6.1
    - 4.6.5
    - 4.7.0
    - 4.7.1
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.3
    - 2.32.4
  - dependency-name: socket.io
    versions:
    - 2.4.1
